test_that('relative heatmaps preserve score alignment and distinguish high error from missing', {
  path <- plot_device()
  on.exit({grDevices::dev.off(); unlink(path)}, add = TRUE)
  x <- list(mse_all = matrix(c(100, 110, 140, NA_real_), 2), lambda_1_min = 1, lambda_2_min = 0.1)
  args <- list(x = x, lambda_1_all = c(1, 2), lambda_2_all = c(.1, 1))
  z <- do.call(plot_cv, args)
  expect_s3_class(z$plot, 'ggplot')
  expect_equal(z$display_data$score, c(100, 110, 140, NA_real_))
  expect_equal(z$display_data$label, c('0.0%', '10.0%', '>30%', 'NA'))
  expect_equal(z$display_data$selected, c(TRUE, FALSE, FALSE, FALSE))
  expect_equal(z$above_limit_count, 1)
  expect_equal(z$unavailable_count, 1)
  expect_equal(z$display_limits, c(0, .1))
  expect_match(z$plot$labels$caption, 'not a divergence diagnosis', fixed = TRUE)
  mse <- do.call(plot_cv, c(args, list(n_observed = 10)))
  expect_equal(mse$display_data$display, z$display_data$display)
  expect_equal(mse$minimum, 10)
  full <- do.call(plot_cv, c(args, list(relative_limit = NULL, show_values = FALSE)))
  expect_equal(full$above_limit_count, 0)
  expect_equal(full$display_limits, c(0, .4))
  expect_equal(length(full$plot$layers), 2)
  expect_error(do.call(plot_cv, c(args, list(relative_limit = 0))), 'relative_limit')
  expect_error(do.call(plot_cv, c(args, list(show_values = NA))), 'show_values')
})

test_that('zero minima use absolute scores and exact ties remain first in CV order', {
  path <- plot_device()
  on.exit({grDevices::dev.off(); unlink(path)}, add = TRUE)
  x <- list(mse_all = matrix(c(0, 0, 2, 4), 2), lambda_1_min = 1, lambda_2_min = .1)
  z <- plot_cv(x, lambda_1_all = c(1, 2), lambda_2_all = c(.1, 1))
  expect_false(z$relative)
  expect_equal(z$above_limit_count, 0)
  expect_equal(z$display_data$display, c(0, 0, 2, 4))
  expect_equal(z$exact_minima, 2)
  expect_equal(which(z$display_data$selected), 1L)
  expect_match(z$plot$labels$caption, 'absolute SSE', fixed = TRUE)
  x$mse_all[] <- 0
  expect_gt(diff(plot_cv(x, lambda_1_all = c(1, 2), lambda_2_all = c(.1, 1))$display_limits), 0)
})

test_that('separate heatmaps share scales and return printable pages', {
  path <- plot_device()
  on.exit({grDevices::dev.off(); unlink(path)}, add = TRUE)
  x <- list(mse_all = array(7:1, c(1, 1, 7)), lambda_1_row_min = 1,
            lambda_1_col_min = 2, lambda_2_min = 7)
  args <- list(x = x, lambda_1_row_all = 1, lambda_1_col_all = 2, lambda_2_all = 1:7,
               relative_limit = NULL)
  full <- do.call(plot_cv, args)
  subset <- do.call(plot_cv, c(args, list(lambda_2_index = c(7, 2))))
  expect_length(full$plots, 2)
  expect_equal(full$display_limits, subset$display_limits)
  expect_equal(as.character(subset$plot$data$panel), c('lambda[2] == 2', 'lambda[2] == 7'))
  expect_equal(levels(subset$plot$data$panel), c('lambda[2] == 7', 'lambda[2] == 2'))
  expect_equal(sum(subset$plot$data$selected), 1)
})
